### PR TITLE
Fix TrueNAS Plugin

### LINKED ISSUE #8057: TrueNAS Plugin Doesn't Work
First off install instructions for TrueNAS do not work, branch master uses release 12.2 which doesn't have python38 so it fails. Branch 12.3-RELEASE also doesn't work as the repo's do not have python38. The pip instructions some what work in that it will install the program but will be executed by command line meaning it will run as root without a service file.

I'm trying to get the plugins working on 13.1 [here](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/322), I thought the reason I couldn't get it going was because of a missing dependency but that apparently is not the case. If I use the updated .json with the 13.1-RELEASE and python39 it will install but will not be running. If I shell into the jail and run `pip install sickchill` then start the sickchill service it will start, but I don't think that's the right way to fix it plus normal users are not going to know how to do this.

Any idea of what to do to fix this?

### PR DESCRIPTION
**Pull request by jasker5183**
Fixes https://github.com/SickChill/SickChill/issues/8057. Still have no idea why installing the pip version allows the git version to run since it's not calling anything from `/usr/local/lib/python3.9/site-packages/sickchill` but it does. This would also allow the user to use the pip version if they choose as they would just have to update the `/usr/local/etc/rc.d/sickchill` to execute `/usr/local/bin/SickChill` instead.

### CODE REVIEW

**Comment by jasker5183** [comment]
Looking to bring this pull request and issue to a close, who controls this plugin? Is this method of fixing this plugin going to work? Or should I switch the plugin to pip?

**Comment by miigotu** [comment]
I say go ahead and approve this one of it solves your issue. The plugin doesn't seem to have a ton of adoption yet, but I would like to help improve on it. I'm also going to be narrowing the repositories SC maintains, so the upstream might not be here soon, I can always PR here with any fixes I'm the future.

**Comment by jasker5183** [comment]
FYI IX Systems is removing support for Plugin's in early 2025 so this PR might be pointless, I've even moved all the plugin's I used to custom basejails.

**Comment by jasker5183** [comment]
Over more than a year has gone by with this and I've lost all interest. I'm closing this PR and I recommend anyone still using Sickchill to just roll their own basejail.

**Pull request closed without merging**
